//=============================================================================
// Generated by configure_riscv.py on 2025-07-04 21:00:38
// Configuration: embedded
//=============================================================================

`ifndef RISCV_CONFIG_GENERATED_PKG_SV
`define RISCV_CONFIG_GENERATED_PKG_SV

package riscv_config_generated_pkg;

    // Core Configuration
    parameter string  CONFIG_ISA           = "RV32IM";
    parameter integer CONFIG_NUM_CORES     = 1;
    parameter string  CONFIG_PIPELINE_TYPE = "in_order";
    
    // Cache Configuration
    parameter integer CONFIG_ICACHE_SIZE_KB = 4;
    parameter integer CONFIG_ICACHE_WAYS    = 2;
    parameter integer CONFIG_DCACHE_SIZE_KB = 4;
    parameter integer CONFIG_DCACHE_WAYS    = 2;

    // Feature Enables
    parameter bit     CONFIG_BRANCH_PRED_EN = 1;
    parameter string  CONFIG_BRANCH_PRED    = "simple";
    parameter bit     CONFIG_OOO_EN         = 0;
    parameter bit     CONFIG_MMU_EN         = 0;
    parameter bit     CONFIG_FPU_EN         = 0;
    parameter bit     CONFIG_ATOMIC_EN      = 0;
    parameter bit     CONFIG_COMPRESSED_EN  = 0;
    parameter bit     CONFIG_VECTOR_EN      = 0;

    // Peripheral Configuration
    parameter bit     CONFIG_CLINT_EN       = 1;
    parameter bit     CONFIG_PLIC_EN        = 1;
    parameter bit     CONFIG_UART_EN        = 1;
    parameter bit     CONFIG_GPIO_EN        = 1;

endpackage : riscv_config_generated_pkg

`endif // RISCV_CONFIG_GENERATED_PKG_SV
